"""Initial local-first ingestion schema."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    for schema in ("ingestion", "raw", "data", "audit"):
        op.execute(sa.text(f"CREATE SCHEMA IF NOT EXISTS {schema}"))
    uuid = postgresql.UUID(as_uuid=True)
    json_type = postgresql.JSONB()
    op.create_table("connections", sa.Column("id", uuid, primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("engine", sa.String(30), nullable=False), sa.Column("config", json_type, nullable=False), sa.Column("secret_ciphertext", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), schema="ingestion")
    op.create_table("data_sources", sa.Column("id", uuid, primary_key=True), sa.Column("name", sa.String(160), nullable=False, unique=True), sa.Column("description", sa.Text(), nullable=False, server_default=""), sa.Column("source_type", sa.String(30), nullable=False), sa.Column("connection_id", uuid, sa.ForeignKey("ingestion.connections.id")), sa.Column("status", sa.String(30), nullable=False, server_default="ACTIVE"), sa.Column("config", json_type, nullable=False, server_default="{}"), sa.Column("created_by", sa.String(160), nullable=False, server_default="local-user"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), schema="ingestion")
    op.create_table("datasets", sa.Column("id", uuid, primary_key=True), sa.Column("data_source_id", uuid, sa.ForeignKey("ingestion.data_sources.id"), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("schema_name", sa.String(63), nullable=False, server_default="data"), sa.Column("table_name", sa.String(160), nullable=False), sa.Column("load_mode", sa.String(30), nullable=False, server_default="INCREMENTAL_UPSERT"), sa.Column("business_key", sa.JSON(), nullable=False, server_default="[]"), sa.Column("missing_record_behavior", sa.String(30), nullable=False, server_default="IGNORE"), sa.Column("columns", json_type, nullable=False, server_default="{}"), sa.UniqueConstraint("data_source_id", "name"), schema="ingestion")
    op.create_table("validation_rules", sa.Column("id", uuid, primary_key=True), sa.Column("dataset_id", uuid, sa.ForeignKey("ingestion.datasets.id"), nullable=False), sa.Column("column_name", sa.String(160), nullable=False), sa.Column("rule_type", sa.String(40), nullable=False), sa.Column("rule_config", json_type, nullable=False, server_default="{}"), sa.Column("severity", sa.String(20), nullable=False, server_default="ERROR"), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), schema="ingestion")
    op.create_table("file_versions", sa.Column("id", uuid, primary_key=True), sa.Column("data_source_id", uuid, sa.ForeignKey("ingestion.data_sources.id"), nullable=False), sa.Column("filename", sa.String(260), nullable=False), sa.Column("file_size", sa.BigInteger(), nullable=False), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("uploaded_by", sa.String(160), nullable=False), sa.Column("processed_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(30), nullable=False, server_default="RECEIVED"), sa.UniqueConstraint("data_source_id", "sha256"), schema="ingestion")
    op.create_table("load_runs", sa.Column("id", uuid, primary_key=True), sa.Column("data_source_id", uuid, sa.ForeignKey("ingestion.data_sources.id"), nullable=False), sa.Column("file_version_id", uuid, sa.ForeignKey("ingestion.file_versions.id")), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(40), nullable=False, server_default="RUNNING"), sa.Column("rows_read", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("rows_inserted", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("rows_updated", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("rows_unchanged", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("rows_rejected", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("error_count", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("warning_count", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("watermark_before", sa.String(160)), sa.Column("watermark_after", sa.String(160)), sa.Column("configuration_snapshot", json_type, nullable=False, server_default="{}"), schema="ingestion")
    op.create_table("load_run_errors", sa.Column("id", uuid, primary_key=True), sa.Column("run_id", uuid, sa.ForeignKey("ingestion.load_runs.id"), nullable=False), sa.Column("error_type", sa.String(30), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), schema="ingestion")
    op.create_table("quarantine_records", sa.Column("id", uuid, primary_key=True), sa.Column("run_id", uuid, sa.ForeignKey("ingestion.load_runs.id"), nullable=False), sa.Column("dataset", sa.String(160), nullable=False), sa.Column("row_number", sa.BigInteger(), nullable=False), sa.Column("business_key", json_type), sa.Column("raw_record", json_type, nullable=False), sa.Column("column_name", sa.String(160)), sa.Column("value", sa.Text()), sa.Column("rule", sa.String(40), nullable=False), sa.Column("error_code", sa.String(60), nullable=False), sa.Column("error_message", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), schema="raw")
    op.create_table("raw_records", sa.Column("id", uuid, primary_key=True), sa.Column("run_id", uuid, sa.ForeignKey("ingestion.load_runs.id"), nullable=False), sa.Column("row_number", sa.BigInteger(), nullable=False), sa.Column("record", json_type, nullable=False), sa.Column("row_hash", sa.String(64), nullable=False), schema="raw")
    op.create_table("data_records", sa.Column("id", uuid, primary_key=True), sa.Column("dataset_id", uuid, sa.ForeignKey("ingestion.datasets.id"), nullable=False), sa.Column("run_id", uuid, sa.ForeignKey("ingestion.load_runs.id"), nullable=False), sa.Column("business_key_hash", sa.String(64), nullable=False), sa.Column("row_hash", sa.String(64), nullable=False), sa.Column("record", json_type, nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("dataset_id", "business_key_hash"), schema="data")
    op.create_table("audit_events", sa.Column("id", uuid, primary_key=True), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("actor", sa.String(160), nullable=False), sa.Column("object_type", sa.String(80), nullable=False), sa.Column("object_id", uuid), sa.Column("payload", json_type, nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), schema="audit")
    op.create_table("watermarks", sa.Column("id", uuid, primary_key=True), sa.Column("data_source_id", uuid, sa.ForeignKey("ingestion.data_sources.id"), nullable=False, unique=True), sa.Column("value", sa.String(160)), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), schema="ingestion")

def downgrade() -> None:
    for table, schema in [("watermarks","ingestion"),("audit_events","audit"),("data_records","data"),("raw_records","raw"),("quarantine_records","raw"),("load_run_errors","ingestion"),("load_runs","ingestion"),("file_versions","ingestion"),("validation_rules","ingestion"),("datasets","ingestion"),("data_sources","ingestion"),("connections","ingestion")]:
        op.drop_table(table, schema=schema)
    for schema in ("audit", "data", "raw", "ingestion"):
        op.execute(sa.text(f"DROP SCHEMA IF EXISTS {schema}"))
